label: 'Ver página de edición'
tips:
  views-ui-displays:
    label: 'Mostrar en esta vista'
  views-ui-view-admin:
    label: 'Administración de Vista'
  views-ui-format:
    label: 'Formato de salida'
  views-ui-fields:
    label: Campos
    body: 'Si esta vista utiliza campos, ellos están listados aquí. Usted puede hacer click en un campo para configurarlo.'
  views-ui-filter:
    label: 'Filtrar su vista'
  views-ui-filter-operations:
    label: 'Acciones de filtrado'
    body: 'Adicionar, reordenar o eliminar filtros.'
  views-ui-sorts:
    label: 'Ordenar criterios'
    body: 'Controla el orden en que los resultados son mostrados. Haga clic en una regla de clasificación activa para configurarla.'
  views-ui-sorts-operations:
    label: 'Actiones de ordenamiento'
    body: 'Adicionar, reordenar o eliminar reglas de ordenamiento.'
  views-ui-preview:
    label: 'Vista previa'
    body: 'Mostrar una vista previa de la salida de la vista.'
